site_name: SCREEK WORKSHOP
dev_addr: "0.0.0.0:8000"
extra:
  # alternate:
  #   - name: English
  #     link: /en/ 
  #     lang: en
  #   - name: Chineses
  #     link: /cn/
  #     lang: zh
  generator: false
  # consent:
  #   title: Cookie consent
  #   description: >- 
  #     We use cookies to recognize your repeated visits and preferences, as well
  #     as to measure the effectiveness of our documentation and whether users
  #     find what they're searching for. With your consent, you're helping us to
  #     make our documentation better.
  analytics: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback!.
  social:
    - icon: fontawesome/brands/ebay
      link: https://www.ebay.com/str/screekworkshop
      # name: eBay Store

theme:
  name: material
  favicon: images/favicon.png
  icon:
    logo: simple/artstation
  custom_dir: overrides
  language: en
  # 设置主题颜色。(23年3月11日_21时27分_)
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
  palette: 
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - content.action.edit

# 大部分从Tasmato直接引入。
# (23年3月12日_16时52分_)
markdown_extensions:
  - admonition
  - toc:
     permalink: "~"
     toc_depth: 3
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tilde
  # - meta
  - def_list
  - attr_list
  - md_in_html

nav:
  - Welcome: index.md
  - Screek Human presence Sensor 1U: 
      - Frimware Upgrade: 1u/firmware.md
      # - Hilink APP: presence_sensor/hilink_app.md
      # - FAQ: presence_sensor/faq.md